# Generated by Django 2.2.28 on 2025-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refriends', '0003_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
