# Generated by Django 2.2.28 on 2025-11-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refriends', '0004_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='all_users',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
