# Generated by Django 2.2.28 on 2025-11-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refriends', '0005_group_all_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_id',
            field=models.FloatField(default=0),
        ),
    ]
