# Generated by Django 2.2.28 on 2025-12-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refriends', '0006_auto_20251128_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_id',
            field=models.IntegerField(default=0),
        ),
    ]
