# Generated by Django 2.2.28 on 2026-01-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Refriends', '0007_auto_20251210_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_id',
        ),
    ]
